name: Build libimobiledevice Static Libraries

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Dummy
        run: echo "test"
